validates:
  user:
    name_length: 50
    email_length: 255
    password_length: 6

available_locales: ["en"]
default_locale: "en"
remember_me: "1"
users_per: 15
gravatar_size: 90
gravatar_size_user: 50
